window.esdocSearchIndex = [
  [
    "styleguide-api-node/api/services/loglevel.js~alert",
    "variable/index.html#static-variable-ALERT",
    "<span>ALERT</span> <span class=\"search-result-import-path\">styleguide-api-node/api/services/LogLevel.js</span>",
    "variable"
  ],
  [
    "styleguide-api-node/api/services/apierror.js~apierror",
    "class/api/services/APIError.js~APIError.html",
    "<span>APIError</span> <span class=\"search-result-import-path\">styleguide-api-node/api/services/APIError.js</span>",
    "class"
  ],
  [
    "styleguide-api-node/api/controllers/abstractcontroller.js~abstract",
    "class/api/controllers/AbstractController.js~Abstract.html",
    "<span>Abstract</span> <span class=\"search-result-import-path\">styleguide-api-node/api/controllers/AbstractController.js</span>",
    "class"
  ],
  [
    "styleguide-api-node/api/services/abstracterror.js~abstracterror",
    "class/api/services/AbstractError.js~AbstractError.html",
    "<span>AbstractError</span> <span class=\"search-result-import-path\">styleguide-api-node/api/services/AbstractError.js</span>",
    "class"
  ],
  [
    "styleguide-api-node/api/services/abstractlogger.js~abstractlogger",
    "class/api/services/AbstractLogger.js~AbstractLogger.html",
    "<span>AbstractLogger</span> <span class=\"search-result-import-path\">styleguide-api-node/api/services/AbstractLogger.js</span>",
    "class"
  ],
  [
    "styleguide-api-node/api/services/loglevel.js~critical",
    "variable/index.html#static-variable-CRITICAL",
    "<span>CRITICAL</span> <span class=\"search-result-import-path\">styleguide-api-node/api/services/LogLevel.js</span>",
    "variable"
  ],
  [
    "styleguide-api-node/api/models/colormodel.js~color",
    "variable/index.html#static-variable-Color",
    "<span>Color</span> <span class=\"search-result-import-path\">styleguide-api-node/api/models/ColorModel.js</span>",
    "variable"
  ],
  [
    "styleguide-api-node/api/controllers/colorcontroller.js~colorcontroller",
    "class/api/controllers/ColorController.js~ColorController.html",
    "<span>ColorController</span> <span class=\"search-result-import-path\">styleguide-api-node/api/controllers/ColorController.js</span>",
    "class"
  ],
  [
    "styleguide-api-node/api/database/connect.js~connect",
    "class/api/database/Connect.js~Connect.html",
    "<span>Connect</span> <span class=\"search-result-import-path\">styleguide-api-node/api/database/Connect.js</span>",
    "class"
  ],
  [
    "styleguide-api-node/api/services/loglevel.js~debug",
    "variable/index.html#static-variable-DEBUG",
    "<span>DEBUG</span> <span class=\"search-result-import-path\">styleguide-api-node/api/services/LogLevel.js</span>",
    "variable"
  ],
  [
    "styleguide-api-node/api/services/loglevel.js~emergency",
    "variable/index.html#static-variable-EMERGENCY",
    "<span>EMERGENCY</span> <span class=\"search-result-import-path\">styleguide-api-node/api/services/LogLevel.js</span>",
    "variable"
  ],
  [
    "styleguide-api-node/api/services/loglevel.js~error",
    "variable/index.html#static-variable-ERROR",
    "<span>ERROR</span> <span class=\"search-result-import-path\">styleguide-api-node/api/services/LogLevel.js</span>",
    "variable"
  ],
  [
    "styleguide-api-node/api/services/formaterror.js~formaterror",
    "class/api/services/FormatError.js~FormatError.html",
    "<span>FormatError</span> <span class=\"search-result-import-path\">styleguide-api-node/api/services/FormatError.js</span>",
    "class"
  ],
  [
    "styleguide-api-node/api/services/loglevel.js~info",
    "variable/index.html#static-variable-INFO",
    "<span>INFO</span> <span class=\"search-result-import-path\">styleguide-api-node/api/services/LogLevel.js</span>",
    "variable"
  ],
  [
    "styleguide-api-node/api/models/iconmodel.js~icon",
    "variable/index.html#static-variable-Icon",
    "<span>Icon</span> <span class=\"search-result-import-path\">styleguide-api-node/api/models/IconModel.js</span>",
    "variable"
  ],
  [
    "styleguide-api-node/api/controllers/iconcontroller.js~iconcontroller",
    "class/api/controllers/IconController.js~IconController.html",
    "<span>IconController</span> <span class=\"search-result-import-path\">styleguide-api-node/api/controllers/IconController.js</span>",
    "class"
  ],
  [
    "styleguide-api-node/api/services/logger.js~logger",
    "class/api/services/Logger.js~Logger.html",
    "<span>Logger</span> <span class=\"search-result-import-path\">styleguide-api-node/api/services/Logger.js</span>",
    "class"
  ],
  [
    "styleguide-api-node/api/services/loglevel.js~notice",
    "variable/index.html#static-variable-NOTICE",
    "<span>NOTICE</span> <span class=\"search-result-import-path\">styleguide-api-node/api/services/LogLevel.js</span>",
    "variable"
  ],
  [
    "styleguide-api-node/api/models/sizemodel.js~size",
    "variable/index.html#static-variable-Size",
    "<span>Size</span> <span class=\"search-result-import-path\">styleguide-api-node/api/models/SizeModel.js</span>",
    "variable"
  ],
  [
    "styleguide-api-node/api/controllers/sizecontroller.js~sizecontroller",
    "class/api/controllers/SizeController.js~SizeController.html",
    "<span>SizeController</span> <span class=\"search-result-import-path\">styleguide-api-node/api/controllers/SizeController.js</span>",
    "class"
  ],
  [
    "styleguide-api-node/api/models/usermodel.js~user",
    "variable/index.html#static-variable-User",
    "<span>User</span> <span class=\"search-result-import-path\">styleguide-api-node/api/models/UserModel.js</span>",
    "variable"
  ],
  [
    "styleguide-api-node/api/controllers/usercontroller.js~usercontroller",
    "class/api/controllers/UserController.js~UserController.html",
    "<span>UserController</span> <span class=\"search-result-import-path\">styleguide-api-node/api/controllers/UserController.js</span>",
    "class"
  ],
  [
    "styleguide-api-node/api/models/versionmodel.js~version",
    "variable/index.html#static-variable-Version",
    "<span>Version</span> <span class=\"search-result-import-path\">styleguide-api-node/api/models/VersionModel.js</span>",
    "variable"
  ],
  [
    "styleguide-api-node/api/controllers/versioncontroller.js~versioncontroller",
    "class/api/controllers/VersionController.js~VersionController.html",
    "<span>VersionController</span> <span class=\"search-result-import-path\">styleguide-api-node/api/controllers/VersionController.js</span>",
    "class"
  ],
  [
    "styleguide-api-node/api/services/loglevel.js~warning",
    "variable/index.html#static-variable-WARNING",
    "<span>WARNING</span> <span class=\"search-result-import-path\">styleguide-api-node/api/services/LogLevel.js</span>",
    "variable"
  ],
  [
    "styleguide-api-node/api/app.js~app",
    "variable/index.html#static-variable-app",
    "<span>app</span> <span class=\"search-result-import-path\">styleguide-api-node/api/App.js</span>",
    "variable"
  ],
  [
    "api/.external-ecmascript.js~array",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Array",
    "api/.external-ecmascript.js~Array",
    "external"
  ],
  [
    "api/.external-ecmascript.js~arraybuffer",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/ArrayBuffer",
    "api/.external-ecmascript.js~ArrayBuffer",
    "external"
  ],
  [
    "api/.external-ecmascript.js~boolean",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Boolean",
    "api/.external-ecmascript.js~Boolean",
    "external"
  ],
  [
    "api/.external-ecmascript.js~dataview",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/DataView",
    "api/.external-ecmascript.js~DataView",
    "external"
  ],
  [
    "api/.external-ecmascript.js~date",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Date",
    "api/.external-ecmascript.js~Date",
    "external"
  ],
  [
    "api/.external-ecmascript.js~error",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Error",
    "api/.external-ecmascript.js~Error",
    "external"
  ],
  [
    "api/.external-ecmascript.js~evalerror",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/EvalError",
    "api/.external-ecmascript.js~EvalError",
    "external"
  ],
  [
    "api/.external-ecmascript.js~float32array",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Float32Array",
    "api/.external-ecmascript.js~Float32Array",
    "external"
  ],
  [
    "api/.external-ecmascript.js~float64array",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Float64Array",
    "api/.external-ecmascript.js~Float64Array",
    "external"
  ],
  [
    "api/.external-ecmascript.js~function",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Function",
    "api/.external-ecmascript.js~Function",
    "external"
  ],
  [
    "api/.external-ecmascript.js~generator",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Generator",
    "api/.external-ecmascript.js~Generator",
    "external"
  ],
  [
    "api/.external-ecmascript.js~generatorfunction",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/GeneratorFunction",
    "api/.external-ecmascript.js~GeneratorFunction",
    "external"
  ],
  [
    "api/.external-ecmascript.js~infinity",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Infinity",
    "api/.external-ecmascript.js~Infinity",
    "external"
  ],
  [
    "api/.external-ecmascript.js~int16array",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Int16Array",
    "api/.external-ecmascript.js~Int16Array",
    "external"
  ],
  [
    "api/.external-ecmascript.js~int32array",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Int32Array",
    "api/.external-ecmascript.js~Int32Array",
    "external"
  ],
  [
    "api/.external-ecmascript.js~int8array",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Int8Array",
    "api/.external-ecmascript.js~Int8Array",
    "external"
  ],
  [
    "api/.external-ecmascript.js~internalerror",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/InternalError",
    "api/.external-ecmascript.js~InternalError",
    "external"
  ],
  [
    "api/.external-ecmascript.js~json",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/JSON",
    "api/.external-ecmascript.js~JSON",
    "external"
  ],
  [
    "api/.external-ecmascript.js~map",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Map",
    "api/.external-ecmascript.js~Map",
    "external"
  ],
  [
    "api/.external-ecmascript.js~nan",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/NaN",
    "api/.external-ecmascript.js~NaN",
    "external"
  ],
  [
    "api/.external-ecmascript.js~number",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Number",
    "api/.external-ecmascript.js~Number",
    "external"
  ],
  [
    "api/.external-ecmascript.js~object",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Object",
    "api/.external-ecmascript.js~Object",
    "external"
  ],
  [
    "api/.external-ecmascript.js~promise",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Promise",
    "api/.external-ecmascript.js~Promise",
    "external"
  ],
  [
    "api/.external-ecmascript.js~proxy",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Proxy",
    "api/.external-ecmascript.js~Proxy",
    "external"
  ],
  [
    "api/.external-ecmascript.js~rangeerror",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/RangeError",
    "api/.external-ecmascript.js~RangeError",
    "external"
  ],
  [
    "api/.external-ecmascript.js~referenceerror",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/ReferenceError",
    "api/.external-ecmascript.js~ReferenceError",
    "external"
  ],
  [
    "api/.external-ecmascript.js~reflect",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Reflect",
    "api/.external-ecmascript.js~Reflect",
    "external"
  ],
  [
    "api/.external-ecmascript.js~regexp",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/RegExp",
    "api/.external-ecmascript.js~RegExp",
    "external"
  ],
  [
    "api/.external-ecmascript.js~set",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Set",
    "api/.external-ecmascript.js~Set",
    "external"
  ],
  [
    "api/.external-ecmascript.js~string",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/String",
    "api/.external-ecmascript.js~String",
    "external"
  ],
  [
    "api/.external-ecmascript.js~symbol",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Symbol",
    "api/.external-ecmascript.js~Symbol",
    "external"
  ],
  [
    "api/.external-ecmascript.js~syntaxerror",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/SyntaxError",
    "api/.external-ecmascript.js~SyntaxError",
    "external"
  ],
  [
    "api/.external-ecmascript.js~typeerror",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/TypeError",
    "api/.external-ecmascript.js~TypeError",
    "external"
  ],
  [
    "api/.external-ecmascript.js~urierror",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/URIError",
    "api/.external-ecmascript.js~URIError",
    "external"
  ],
  [
    "api/.external-ecmascript.js~uint16array",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Uint16Array",
    "api/.external-ecmascript.js~Uint16Array",
    "external"
  ],
  [
    "api/.external-ecmascript.js~uint32array",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Uint32Array",
    "api/.external-ecmascript.js~Uint32Array",
    "external"
  ],
  [
    "api/.external-ecmascript.js~uint8array",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Uint8Array",
    "api/.external-ecmascript.js~Uint8Array",
    "external"
  ],
  [
    "api/.external-ecmascript.js~uint8clampedarray",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Uint8ClampedArray",
    "api/.external-ecmascript.js~Uint8ClampedArray",
    "external"
  ],
  [
    "api/.external-ecmascript.js~weakmap",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/WeakMap",
    "api/.external-ecmascript.js~WeakMap",
    "external"
  ],
  [
    "api/.external-ecmascript.js~weakset",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/WeakSet",
    "api/.external-ecmascript.js~WeakSet",
    "external"
  ],
  [
    "api/.external-ecmascript.js~boolean",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Boolean",
    "api/.external-ecmascript.js~boolean",
    "external"
  ],
  [
    "api/.external-ecmascript.js~function",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Function",
    "api/.external-ecmascript.js~function",
    "external"
  ],
  [
    "api/.external-ecmascript.js~null",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/null",
    "api/.external-ecmascript.js~null",
    "external"
  ],
  [
    "api/.external-ecmascript.js~number",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Number",
    "api/.external-ecmascript.js~number",
    "external"
  ],
  [
    "api/.external-ecmascript.js~object",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Object",
    "api/.external-ecmascript.js~object",
    "external"
  ],
  [
    "api/.external-ecmascript.js~string",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/String",
    "api/.external-ecmascript.js~string",
    "external"
  ],
  [
    "api/.external-ecmascript.js~undefined",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/undefined",
    "api/.external-ecmascript.js~undefined",
    "external"
  ],
  [
    "api/app.js",
    "file/api/App.js.html",
    "api/App.js",
    "file"
  ],
  [
    "api/configs/index.js",
    "file/api/configs/index.js.html",
    "api/configs/index.js",
    "file"
  ],
  [
    "api/controllers/abstractcontroller.js",
    "file/api/controllers/AbstractController.js.html",
    "api/controllers/AbstractController.js",
    "file"
  ],
  [
    "api/controllers/abstractcontroller.js~abstract#_model",
    "class/api/controllers/AbstractController.js~Abstract.html#instance-member-_model",
    "api/controllers/AbstractController.js~Abstract#_model",
    "member"
  ],
  [
    "api/controllers/abstractcontroller.js~abstract#constructor",
    "class/api/controllers/AbstractController.js~Abstract.html#instance-constructor-constructor",
    "api/controllers/AbstractController.js~Abstract#constructor",
    "method"
  ],
  [
    "api/controllers/abstractcontroller.js~abstract#create",
    "class/api/controllers/AbstractController.js~Abstract.html#instance-method-create",
    "api/controllers/AbstractController.js~Abstract#create",
    "method"
  ],
  [
    "api/controllers/abstractcontroller.js~abstract#getbyname",
    "class/api/controllers/AbstractController.js~Abstract.html#instance-method-getByName",
    "api/controllers/AbstractController.js~Abstract#getByName",
    "method"
  ],
  [
    "api/controllers/abstractcontroller.js~abstract#getlist",
    "class/api/controllers/AbstractController.js~Abstract.html#instance-method-getList",
    "api/controllers/AbstractController.js~Abstract#getList",
    "method"
  ],
  [
    "api/controllers/abstractcontroller.js~abstract#isempty",
    "class/api/controllers/AbstractController.js~Abstract.html#instance-method-isEmpty",
    "api/controllers/AbstractController.js~Abstract#isEmpty",
    "method"
  ],
  [
    "api/controllers/colorcontroller.js",
    "file/api/controllers/ColorController.js.html",
    "api/controllers/ColorController.js",
    "file"
  ],
  [
    "api/controllers/colorcontroller.js~colorcontroller#constructor",
    "class/api/controllers/ColorController.js~ColorController.html#instance-constructor-constructor",
    "api/controllers/ColorController.js~ColorController#constructor",
    "method"
  ],
  [
    "api/controllers/iconcontroller.js",
    "file/api/controllers/IconController.js.html",
    "api/controllers/IconController.js",
    "file"
  ],
  [
    "api/controllers/iconcontroller.js~iconcontroller#constructor",
    "class/api/controllers/IconController.js~IconController.html#instance-constructor-constructor",
    "api/controllers/IconController.js~IconController#constructor",
    "method"
  ],
  [
    "api/controllers/sizecontroller.js",
    "file/api/controllers/SizeController.js.html",
    "api/controllers/SizeController.js",
    "file"
  ],
  [
    "api/controllers/sizecontroller.js~sizecontroller#constructor",
    "class/api/controllers/SizeController.js~SizeController.html#instance-constructor-constructor",
    "api/controllers/SizeController.js~SizeController#constructor",
    "method"
  ],
  [
    "api/controllers/usercontroller.js",
    "file/api/controllers/UserController.js.html",
    "api/controllers/UserController.js",
    "file"
  ],
  [
    "api/controllers/usercontroller.js~usercontroller#constructor",
    "class/api/controllers/UserController.js~UserController.html#instance-constructor-constructor",
    "api/controllers/UserController.js~UserController#constructor",
    "method"
  ],
  [
    "api/controllers/versioncontroller.js",
    "file/api/controllers/VersionController.js.html",
    "api/controllers/VersionController.js",
    "file"
  ],
  [
    "api/controllers/versioncontroller.js~versioncontroller#constructor",
    "class/api/controllers/VersionController.js~VersionController.html#instance-constructor-constructor",
    "api/controllers/VersionController.js~VersionController#constructor",
    "method"
  ],
  [
    "api/database/connect.js",
    "file/api/database/Connect.js.html",
    "api/database/Connect.js",
    "file"
  ],
  [
    "api/database/connect.js~connect#_configs",
    "class/api/database/Connect.js~Connect.html#instance-member-_configs",
    "api/database/Connect.js~Connect#_configs",
    "member"
  ],
  [
    "api/database/connect.js~connect#constructor",
    "class/api/database/Connect.js~Connect.html#instance-constructor-constructor",
    "api/database/Connect.js~Connect#constructor",
    "method"
  ],
  [
    "api/database/connect.js~connect#initialize",
    "class/api/database/Connect.js~Connect.html#instance-method-initialize",
    "api/database/Connect.js~Connect#initialize",
    "method"
  ],
  [
    "api/database/connect.js~connect#setdebug",
    "class/api/database/Connect.js~Connect.html#instance-method-setDebug",
    "api/database/Connect.js~Connect#setDebug",
    "method"
  ],
  [
    "api/models/colormodel.js",
    "file/api/models/ColorModel.js.html",
    "api/models/ColorModel.js",
    "file"
  ],
  [
    "api/models/iconmodel.js",
    "file/api/models/IconModel.js.html",
    "api/models/IconModel.js",
    "file"
  ],
  [
    "api/models/sizemodel.js",
    "file/api/models/SizeModel.js.html",
    "api/models/SizeModel.js",
    "file"
  ],
  [
    "api/models/usermodel.js",
    "file/api/models/UserModel.js.html",
    "api/models/UserModel.js",
    "file"
  ],
  [
    "api/models/versionmodel.js",
    "file/api/models/VersionModel.js.html",
    "api/models/VersionModel.js",
    "file"
  ],
  [
    "api/routes/iconroutes.js",
    "file/api/routes/IconRoutes.js.html",
    "api/routes/IconRoutes.js",
    "file"
  ],
  [
    "api/routes/userroutes.js",
    "file/api/routes/UserRoutes.js.html",
    "api/routes/UserRoutes.js",
    "file"
  ],
  [
    "api/routes/index.js",
    "file/api/routes/index.js.html",
    "api/routes/index.js",
    "file"
  ],
  [
    "api/services/apierror.js",
    "file/api/services/APIError.js.html",
    "api/services/APIError.js",
    "file"
  ],
  [
    "api/services/apierror.js~apierror#constructor",
    "class/api/services/APIError.js~APIError.html#instance-constructor-constructor",
    "api/services/APIError.js~APIError#constructor",
    "method"
  ],
  [
    "api/services/abstracterror.js",
    "file/api/services/AbstractError.js.html",
    "api/services/AbstractError.js",
    "file"
  ],
  [
    "api/services/abstracterror.js~abstracterror#constructor",
    "class/api/services/AbstractError.js~AbstractError.html#instance-constructor-constructor",
    "api/services/AbstractError.js~AbstractError#constructor",
    "method"
  ],
  [
    "api/services/abstracterror.js~abstracterror#isoperational",
    "class/api/services/AbstractError.js~AbstractError.html#instance-member-isOperational",
    "api/services/AbstractError.js~AbstractError#isOperational",
    "member"
  ],
  [
    "api/services/abstracterror.js~abstracterror#ispublic",
    "class/api/services/AbstractError.js~AbstractError.html#instance-member-isPublic",
    "api/services/AbstractError.js~AbstractError#isPublic",
    "member"
  ],
  [
    "api/services/abstracterror.js~abstracterror#message",
    "class/api/services/AbstractError.js~AbstractError.html#instance-member-message",
    "api/services/AbstractError.js~AbstractError#message",
    "member"
  ],
  [
    "api/services/abstracterror.js~abstracterror#name",
    "class/api/services/AbstractError.js~AbstractError.html#instance-member-name",
    "api/services/AbstractError.js~AbstractError#name",
    "member"
  ],
  [
    "api/services/abstracterror.js~abstracterror#status",
    "class/api/services/AbstractError.js~AbstractError.html#instance-member-status",
    "api/services/AbstractError.js~AbstractError#status",
    "member"
  ],
  [
    "api/services/abstractlogger.js",
    "file/api/services/AbstractLogger.js.html",
    "api/services/AbstractLogger.js",
    "file"
  ],
  [
    "api/services/abstractlogger.js~abstractlogger#alert",
    "class/api/services/AbstractLogger.js~AbstractLogger.html#instance-method-alert",
    "api/services/AbstractLogger.js~AbstractLogger#alert",
    "method"
  ],
  [
    "api/services/abstractlogger.js~abstractlogger#constructor",
    "class/api/services/AbstractLogger.js~AbstractLogger.html#instance-constructor-constructor",
    "api/services/AbstractLogger.js~AbstractLogger#constructor",
    "method"
  ],
  [
    "api/services/abstractlogger.js~abstractlogger#critical",
    "class/api/services/AbstractLogger.js~AbstractLogger.html#instance-method-critical",
    "api/services/AbstractLogger.js~AbstractLogger#critical",
    "method"
  ],
  [
    "api/services/abstractlogger.js~abstractlogger#debug",
    "class/api/services/AbstractLogger.js~AbstractLogger.html#instance-method-debug",
    "api/services/AbstractLogger.js~AbstractLogger#debug",
    "method"
  ],
  [
    "api/services/abstractlogger.js~abstractlogger#emergency",
    "class/api/services/AbstractLogger.js~AbstractLogger.html#instance-method-emergency",
    "api/services/AbstractLogger.js~AbstractLogger#emergency",
    "method"
  ],
  [
    "api/services/abstractlogger.js~abstractlogger#error",
    "class/api/services/AbstractLogger.js~AbstractLogger.html#instance-method-error",
    "api/services/AbstractLogger.js~AbstractLogger#error",
    "method"
  ],
  [
    "api/services/abstractlogger.js~abstractlogger#implementationrequired",
    "class/api/services/AbstractLogger.js~AbstractLogger.html#instance-method-implementationRequired",
    "api/services/AbstractLogger.js~AbstractLogger#implementationRequired",
    "method"
  ],
  [
    "api/services/abstractlogger.js~abstractlogger#info",
    "class/api/services/AbstractLogger.js~AbstractLogger.html#instance-method-info",
    "api/services/AbstractLogger.js~AbstractLogger#info",
    "method"
  ],
  [
    "api/services/abstractlogger.js~abstractlogger#log",
    "class/api/services/AbstractLogger.js~AbstractLogger.html#instance-method-log",
    "api/services/AbstractLogger.js~AbstractLogger#log",
    "method"
  ],
  [
    "api/services/abstractlogger.js~abstractlogger#notice",
    "class/api/services/AbstractLogger.js~AbstractLogger.html#instance-method-notice",
    "api/services/AbstractLogger.js~AbstractLogger#notice",
    "method"
  ],
  [
    "api/services/abstractlogger.js~abstractlogger#warning",
    "class/api/services/AbstractLogger.js~AbstractLogger.html#instance-method-warning",
    "api/services/AbstractLogger.js~AbstractLogger#warning",
    "method"
  ],
  [
    "api/services/formaterror.js",
    "file/api/services/FormatError.js.html",
    "api/services/FormatError.js",
    "file"
  ],
  [
    "api/services/formaterror.js~formaterror.makepretty",
    "class/api/services/FormatError.js~FormatError.html#static-method-makePretty",
    "api/services/FormatError.js~FormatError.makePretty",
    "method"
  ],
  [
    "api/services/loglevel.js",
    "file/api/services/LogLevel.js.html",
    "api/services/LogLevel.js",
    "file"
  ],
  [
    "api/services/logger.js",
    "file/api/services/Logger.js.html",
    "api/services/Logger.js",
    "file"
  ],
  [
    "api/services/logger.js~logger#alert",
    "class/api/services/Logger.js~Logger.html#instance-method-alert",
    "api/services/Logger.js~Logger#alert",
    "method"
  ],
  [
    "api/services/logger.js~logger#constructor",
    "class/api/services/Logger.js~Logger.html#instance-constructor-constructor",
    "api/services/Logger.js~Logger#constructor",
    "method"
  ],
  [
    "api/services/logger.js~logger#critical",
    "class/api/services/Logger.js~Logger.html#instance-method-critical",
    "api/services/Logger.js~Logger#critical",
    "method"
  ],
  [
    "api/services/logger.js~logger#debug",
    "class/api/services/Logger.js~Logger.html#instance-method-debug",
    "api/services/Logger.js~Logger#debug",
    "method"
  ],
  [
    "api/services/logger.js~logger#emergency",
    "class/api/services/Logger.js~Logger.html#instance-method-emergency",
    "api/services/Logger.js~Logger#emergency",
    "method"
  ],
  [
    "api/services/logger.js~logger#error",
    "class/api/services/Logger.js~Logger.html#instance-method-error",
    "api/services/Logger.js~Logger#error",
    "method"
  ],
  [
    "api/services/logger.js~logger#info",
    "class/api/services/Logger.js~Logger.html#instance-method-info",
    "api/services/Logger.js~Logger#info",
    "method"
  ],
  [
    "api/services/logger.js~logger#isdev",
    "class/api/services/Logger.js~Logger.html#instance-member-isDev",
    "api/services/Logger.js~Logger#isDev",
    "member"
  ],
  [
    "api/services/logger.js~logger#isprod",
    "class/api/services/Logger.js~Logger.html#instance-member-isProd",
    "api/services/Logger.js~Logger#isProd",
    "member"
  ],
  [
    "api/services/logger.js~logger#log",
    "class/api/services/Logger.js~Logger.html#instance-method-log",
    "api/services/Logger.js~Logger#log",
    "method"
  ],
  [
    "api/services/logger.js~logger#notice",
    "class/api/services/Logger.js~Logger.html#instance-method-notice",
    "api/services/Logger.js~Logger#notice",
    "method"
  ],
  [
    "api/services/logger.js~logger#warning",
    "class/api/services/Logger.js~Logger.html#instance-method-warning",
    "api/services/Logger.js~Logger#warning",
    "method"
  ]
]